libnvidia-container-tools: remove buildpath from nvidia-modprobe compilation
OE4T/meta-tegra pull request #1035
Opened 2022-08-20 01:11 UTC by atharvanan1

This fixes following Package QA warning:
```
WARNING: libnvidia-container-tools-1.9.0-r0 do_package_qa: QA Issue: File /usr/lib/libnvidia-container.a in package libnvidia-container-tools-staticdev contains reference to TMPDIR [buildpaths]
WARNING: libnvidia-container-tools-1.9.0-r0 do_package_qa: QA Issue: File /usr/lib/.debug/libnvidia-container.so.1.9.0 in package libnvidia-container-tools-dbg contains reference to TMPDIR
File /usr/lib/debug/usr/lib/.debug/libnvidia-container.so.1 in package libnvidia-container-tools-dbg contains reference to TMPDIR [buildpaths]
```

Signed-off-by: Atharva Nandanwar <anandanwar@sighthound.com>

2022-08-20 12:08 UTC, madisongh requested changes
See in-line.

Let's skip handling the remaining `rpcgen`-derived embedded path issues for now.  Adding `buildpaths` to `INSANE_SKIP:${PN}-src` should silence the warning.

2022-08-20 20:49 UTC, atharvanan1 commented on external/virtualization-layer/recipes-containers/libnvidia-container-tools/libnvidia-container-tools/0003-fix-remove-buildpath-for-package-qa.patch
> ++CFLAGS   += -ffile-prefix-map=$(GIT_CEILING_DIRECTORIES)=/usr/src/debug/libnvidia-container/1.9.0-r0
Thanks for this advice!

2022-08-20 20:49 UTC, atharvanan1 commented
@madisongh Should be ready now! Let me know if you have any inputs on this.

2022-08-21 10:59 UTC, madisongh approved these changes

2022-08-21 10:59 UTC, merged