arm-trusted-firmware: set DEBUG and LOG_LEVEL from bitbake
OE4T/meta-tegra pull request #1699
Opened 2024-09-18 15:52 UTC by atharvanan1

- this allows ability to modify these in other layers if needed

2024-09-18 15:56 UTC, ichergui requested changes

2024-09-18 15:56 UTC, ichergui commented on recipes-bsp/arm-trusted-firmware/arm-trusted-firmware_2.8-l4t-r36.3.0.bb
> +DEBUG ?= "0"
I prefer to have those variables specific to `ATF`.
It should be something as below:
```
ATF_DEBUG ?= "0"
ATF_LOG_LEVEL ?= "20"
```

2024-09-18 16:23 UTC, atharvanan1 commented
I'll move this to `scarthgap`, `scarthgap-l4t-35.x` and `kirkstone`

2024-09-19 16:26 UTC, atharvanan1 commented
@ichergui Please merge this whenever it seems fit.

2024-09-19 16:29 UTC, ichergui commented
@atharvanan1 I don't have the permissions to merge this PR. I'm waiting for @madisongh to do that

2024-09-19 21:12 UTC, merged

2024-09-23 18:06 UTC, atharvanan1 commented
Thanks for review and merge on this! @ichergui and @madisongh