Replace deprecated CVE_CHECK_IGNORE with CVE_STATUS
OE4T/meta-tegra pull request #1737
Opened 2024-10-25 19:40 UTC by yumiweidemao

Per [Yocto manual](https://docs.yoctoproject.org/ref-manual/variables.html#term-CVE_CHECK_IGNORE), CVE_CHECK_IGNORE has been deprecated and should be replaced by CVE_STATUS.

When building with openembedded-core, there is a fallback mechanism in [cve-check.bbclass](https://github.com/openembedded/openembedded-core/blob/master/meta/classes/cve-check.bbclass#L102) but it will print some noisy warning messages.

This pull request is to replace the deprecated CVE_CHECK_IGNORE with CVE_STATUS.

2024-10-25 19:41 UTC, ichergui approved these changes
LGTM. Thanks @yumiweidemao

2024-10-25 19:43 UTC, ichergui requested changes
@yumiweidemao  Could you please add `Signed-off-by` ? So, we can merge the PR 
Thanks

2024-10-25 19:45 UTC, yumiweidemao commented
@ichergui Signoff added. Thanks!

2024-10-25 20:17 UTC, madisongh requested changes

2024-10-25 20:17 UTC, madisongh commented on recipes-devtools/gcc-for-nvcc/gcc-for-nvcc-10.3.inc
> +CVE_STATUS[CVE-2021-37322] = "ignored"
This should specify the actual reason. Looking at the setting in OE-Core's gcc recipe, it should be `"cpe-incorrect: Is a binutils 2.26 issue, not gcc"`.

2024-10-25 20:25 UTC, yumiweidemao commented on recipes-devtools/gcc-for-nvcc/gcc-for-nvcc-10.3.inc
> +CVE_STATUS[CVE-2021-37322] = "ignored"
Modified the comment

2024-10-26 10:50 UTC, madisongh commented on recipes-devtools/gcc-for-nvcc/gcc-for-nvcc-10.3.inc
> +CVE_STATUS[CVE-2021-37322] = "ignored"
It's the setting that needs changing, and the comment should be removed.  See corresponding line in the [current gcc recipe](https://git.yoctoproject.org/poky/tree/meta/recipes-devtools/gcc/gcc-14.2.inc#n111).

2024-10-28 14:55 UTC, yumiweidemao commented on recipes-devtools/gcc-for-nvcc/gcc-for-nvcc-10.3.inc
> +CVE_STATUS[CVE-2021-37322] = "ignored"
Modified the line. Thanks for the clarification!

2024-10-28 15:14 UTC, merged