virglrenderer depends on gbm.h
OE4T/meta-tegra pull request #718
Opened 2021-05-27 21:46 UTC by jwinarske

Signed-off-by: Joel Winarske <joel.winarske@gmail.com>

This enables the building of qemu package without changing qemu's package config.

2021-05-27 23:26 UTC, ichergui requested changes
Could we add only `libgbm-dev` in the dependecy list instead of `virtual/mesa` ?

2021-05-28 00:03 UTC, jwinarske commented
> Could we add only `libgbm-dev` in the dependecy list instead of `virtual/mesa` ?

```
ERROR: Nothing PROVIDES 'libgbm-dev' (but /home/joel/tegra-demo-distro/layers/meta/recipes-graphics/virglrenderer/virglrenderer_0.9.1.bb DEPENDS on or otherwise requires it). Close matches:
  libgudev
  mesa RPROVIDES libgbm-dev
ERROR: Required build target 'virglrenderer' has no buildable providers.
Missing or unbuildable dependency chain was: ['virglrenderer', 'libgbm-dev']

Summary: There was 1 WARNING message shown.
```

Mesa will need to come in at some point based on this MR: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/9902

2021-05-28 00:06 UTC, jwinarske commented
Actually I think we want `virtual/libgbm`

2021-05-28 08:31 UTC, ichergui approved these changes

2021-05-28 11:29 UTC, madisongh requested changes
We can't take this one as is, since we'd be modifying the dependencies for the recipe for all platforms, which is a no-no for a BSP layer.

If it's generally applicable (and the needed header just happens to be present due to transitive dependencies), the fix should be submitted as a patch upstream to OE-Core.

If it's really specific to the tegra targets only, we can do this with `DEPENDS_append_tegra` and then set `PACKAGE_ARCH = "${TEGRA_PKGARCH}"`, so the modification only applies to our platforms.

If it is generally applicable, and you do submit the patch upstream, I'll also accept the modified append approach as a temporary workaround until the patch makes it into OE-Core.

Finally, since `virglrenderer` is in OE-Core, this bbappend belongs in in the core part of the tree, not under `external/virtualization-layer`.

2021-05-28 15:55 UTC, jwinarske commented
I think that NVIDIA is the only entity that has avoided Mesa for all these years.  The MR referenced is indicating that is about to change; it enables loading of proprietary driver.

I suspect if it were an issue on other targets it would have already been accounted for upstream.

Given gbm is a hard dependency for virglrenderer, and tegra being the exception perhaps `DEPENDS_append_tegra` is sufficient?

2021-05-28 15:58 UTC, jwinarske commented
I'll ask upstream about it

2021-05-28 19:17 UTC, jwinarske commented
Patch sent up stream for poky recipe, waiting on review.

2021-06-07 12:24 UTC, madisongh commented
Looks like the upstream patch [made it in](https://git.openembedded.org/openembedded-core/commit/?id=fd807dfa2ec25111dd359ec87d197020e747cf0d), so we should be OK to close this.

2021-06-07 12:24 UTC, closed without merging