ds-tlt: Add recipe for tlt samples and custom parser
OE4T/meta-tegra pull request #802
Opened 2021-09-23 21:08 UTC by bcis93

This PR adds a recipe that builds several deepstream tlt sample apps as well as the `libnvds_infercustomparser_tlt.so` custom parser library from NVIDIA's https://github.com/NVIDIA-AI-IOT/deepstream_tao_apps repository.

What I really care about here is the `libnvds_infercustomparser_tlt.so` library to build custom bounding box parsers (see the build instructions [here](https://docs.nvidia.com/metropolis/TLT/tlt-user-guide/text/object_detection/yolo_v4.html#prerequisites-for-yolov4-model)), but I figured since I'm already pulling from this repo it would be more appropriate to build everything in the repo (meaning the tlt sample apps as well).

I also separated the samples and custom parser into separate packages so that the custom parser can be built by itself if desired.

I'm opening this PR as a draft for now as I'm finishing up some testing, but please let me know if you have any feedback. I'm targeting the `dunfell-l4t-r32.4.3` branch since that's what my image is based on, but I can also open another PR targeting the master branch once this one gets approved.

2021-09-23 23:55 UTC, ichergui commented
Hello @bcis93 
I think this PR should be [here](https://github.com/OE4T/meta-tegra-community)
We should keep `meta-tegra` close to Nvidia's  `Jetpack` / `L4T`

2021-09-24 13:56 UTC, madisongh requested changes
A few comments in-line.

As @ichergui mentioned, this is more appropriate for the meta-tegra-community repo, since it's not building/installing BSP or JetPack-related content.

Thanks!

2021-09-24 13:56 UTC, madisongh commented on recipes-devtools/deepstream/deepstream-tlt-apps_3.0.bb
> +EXTRA_OEMAKE += " CC='${CXX}' CUDA_VER=${CUDA_VERSION}"
Looking at the makefiles, there are a couple more variables that look like they need overriding here. 
 In particular, I see DS_VER and TARGET_DEVICE getting set by running `deepstream-app` and `gcc` via `$(shell)` directives... neither of which will work very well in a cross-build environment.

2021-09-24 13:56 UTC, madisongh commented on recipes-devtools/deepstream/deepstream-tlt-apps_3.0.bb
> +inherit pkgconfig cuda
The recipe needs a
```
COMPATIBLE_MACHINE = "(tegra)"
```
line to prevent it from being parsed for non-tegra builds.

2021-09-24 13:56 UTC, madisongh commented on recipes-devtools/deepstream/deepstream-tlt-apps_3.0.bb
> +TARGET_CC_ARCH += "${LDFLAGS}"
This is kind of ugly, but given the way the makefiles are written, it's probably the best way to ensure that the linker flags get used.

2021-09-24 13:56 UTC, madisongh commented on recipes-devtools/deepstream/deepstream-tlt-apps_3.0.bb
> +RDEPENDS_${PN}-samples += "deepstream-5.0"
I'm not sure this dependency is necessary?  If the samples link against the DS libraries, the runtime dependency should get discovered automatically.

2021-09-24 14:35 UTC, bcis93 commented
Thanks for the feedback @ichergui and @madisongh! I’ll get the changes made and move this over to meta-tegra-community this weekend

2021-09-28 04:37 UTC, closed without merging