external/qt5-layer: fix egldevice backend for L4T 32.7.1
OE4T/meta-tegra pull request #960
Opened 2022-04-15 15:31 UTC by kekiefer

This change adds two patches to support tegra devices in qt5 with
the L4T release 32.7.1. The newer version of L4T appears to unify
the capabilities of tegra-udrm and drm-nvdc drivers in the NVIDIA's
libdrm, and this enables us to more easily support Qt using either
method, but does require some fixups.

The first patch is a backport from newer versions of Qt which will
allow the egldevice backend to function with the tegra-udrm. It is
not strictly necessary, but is nice because then users don't have
to worry about removing this driver if they want to e.g. switch
between Weston and Qt.

The second patch adds a default framebuffer to the initial calls
to libdrm to set modes and planes. The default value of -1 that was
used by Qt before wouldn't have been valid for any other platform,
and now it is not valid for tegra either.

Fixes #956

Signed-off-by: Kurt Kiefer <kurt.kiefer@arthrex.com>

2022-04-15 16:00 UTC, madisongh requested changes
Thanks for doing the backport - I wasn't sure if it could just be cherry-picked from master or not.

One nitpick in-line, otherwise LGTM

2022-04-15 16:11 UTC, kekiefer commented
Done.

I admit to not having tested this Dunfell version, since I don't have the infrastructure to switch over to the branch at this time. The patches should be fine since there's been very little movement on this backend for quite some time. Maybe it's best to hold off on merging this pending feedback from @benediktley

2022-04-15 20:23 UTC, benediktley commented
Thanks a lot for the patch. I will provide feedback by end of next week. I am on a vacation trip and have no access to any jetson device.

2022-04-28 15:18 UTC, kekiefer commented
@benediktley have you had a chance to review this fix for dunfell?

2022-04-28 16:01 UTC, benediktley commented
@kekiefer: Sorry for the late response. I did some tests on my project using your patches but still have no video output on the dunfell branch. The log shows the dumb fb debug entries from the patches but nothing that helps to identify the issue.

2022-04-28 16:24 UTC, kekiefer commented
Strange, the stack should be equivalent. One thing to try is loading the tegra-udrm driver, `modprobe tegra-udrm modeset=1` and see if you have better luck with this?

2022-04-29 12:06 UTC, benediktley commented
Also tested with loaded tegra-udrm module. The log shows that /dev/dri/card0 is used but other than that no difference. I am using DISTRO_FEATURES egl, gles and opengl (no x11 or wayland) and Qt PACKAGECONFIG kms, gles2 and eglfs.

Here is my full log when starting the eglfs application:

> QML debugging is enabled. Only use this in a safe environment.
qt.qpa.egldeviceintegration: EGL device integration plugin keys: ("eglfs_emu", "eglfs_kms_egldevice", "eglfs_kms")
qt.qpa.egldeviceintegration: EGL device integration plugin keys (sorted): ("eglfs_kms_egldevice", "eglfs_kms", "eglfs_emu")
qt.qpa.egldeviceintegration: Trying to load device EGL integration "eglfs_kms_egldevice"
qt.qpa.eglfs.kms: New DRM/KMS on EGLDevice integration created
qt.qpa.egldeviceintegration: Using EGL device integration "eglfs_kms_egldevice"
qt.qpa.eglfs.kms: platformInit: Opening DRM device
qt.qpa.eglfs.kms: Found 1 EGL devices
qt.qpa.eglfs.kms: Using backend-provided DRM device /dev/dri/card0
qt.qpa.eglfs.kms: Creating display
qt.qpa.eglfs.kms: Atomic reported as supported
qt.qpa.eglfs.kms: Atomic disabled
qt.qpa.eglfs.kms: Found 8 planes
qt.qpa.eglfs.kms: plane 0: id = 4000 countFormats = 34 possibleCrtcs = 0x1 supported formats = RA12 AR15 RA15 RG16 XR24 XB24 AR24 AB24 AR30 AB30 AB4H R101 R100 B101 B100 AS24 XS24 YUYV UYVY NV12 NV21 NV16 NV61 NV24 NV42 YU12 YV12 YU24 YV24 P210 P010 P012 HD01 UHD0 
qt.qpa.eglfs.kms:   property 0: id = 40000 name = 'SRC_X'
qt.qpa.eglfs.kms:   type is RANGE, value is 0, possible values are:
qt.qpa.eglfs.kms:     0
qt.qpa.eglfs.kms:   property 1: id = 40001 name = 'SRC_Y'
qt.qpa.eglfs.kms:   type is RANGE, value is 0, possible values are:
qt.qpa.eglfs.kms:     0
qt.qpa.eglfs.kms:   property 2: id = 40002 name = 'SRC_W'
qt.qpa.eglfs.kms:   type is RANGE, value is 0, possible values are:
qt.qpa.eglfs.kms:     0
qt.qpa.eglfs.kms:   property 3: id = 40003 name = 'SRC_H'
qt.qpa.eglfs.kms:   type is RANGE, value is 0, possible values are:
qt.qpa.eglfs.kms:     0
qt.qpa.eglfs.kms:   property 4: id = 40004 name = 'zpos'
qt.qpa.eglfs.kms:   type is RANGE, value is 10, possible values are:
qt.qpa.eglfs.kms:     10
qt.qpa.eglfs.kms:   property 5: id = 40005 name = 'alpha'
qt.qpa.eglfs.kms:   type is RANGE, value is 255, possible values are:
qt.qpa.eglfs.kms:     255
qt.qpa.eglfs.kms:   property 6: id = 40006 name = 'CRTC_X'
qt.qpa.eglfs.kms:   type is RANGE, value is 0, possible values are:
qt.qpa.eglfs.kms:     0
qt.qpa.eglfs.kms:   property 7: id = 40007 name = 'CRTC_Y'
qt.qpa.eglfs.kms:   type is RANGE, value is 0, possible values are:
qt.qpa.eglfs.kms:     0
qt.qpa.eglfs.kms:   property 8: id = 40008 name = 'CRTC_W'
qt.qpa.eglfs.kms:   type is RANGE, value is 0, possible values are:
qt.qpa.eglfs.kms:     0
qt.qpa.eglfs.kms:   property 9: id = 40009 name = 'CRTC_H'
qt.qpa.eglfs.kms:   type is RANGE, value is 0, possible values are:
qt.qpa.eglfs.kms:     0
qt.qpa.eglfs.kms:   property 10: id = 40010 name = 'CRTC_ID'
qt.qpa.eglfs.kms:   type is OBJECT
qt.qpa.eglfs.kms:   property 11: id = 40011 name = 'FB_ID'
qt.qpa.eglfs.kms:   type is OBJECT
qt.qpa.eglfs.kms:   property 12: id = 40012 name = 'IN_FENCE_FD'
qt.qpa.eglfs.kms:   type is OBJECT
qt.qpa.eglfs.kms:   property 13: id = 40013 name = 'IN_FORMATS'
qt.qpa.eglfs.kms:   type is BLOB
qt.qpa.eglfs.kms:   property 14: id = 40014 name = 'pixel blend mode'
qt.qpa.eglfs.kms:   type is ENUM, value is 1, possible values are:
qt.qpa.eglfs.kms:     enum 0: None - 0
qt.qpa.eglfs.kms:     enum 1: Pre-multiplied - 1
qt.qpa.eglfs.kms:     enum 2: Coverage - 2
qt.qpa.eglfs.kms:   property 15: id = 40015 name = 'color range'
qt.qpa.eglfs.kms:   type is ENUM, value is 0, possible values are:
qt.qpa.eglfs.kms:     enum 0: Full - 0
qt.qpa.eglfs.kms:     enum 1: Limited - 1
qt.qpa.eglfs.kms:   property 16: id = 40016 name = 'type'
qt.qpa.eglfs.kms:   type is ENUM, value is 0, possible values are:
qt.qpa.eglfs.kms:     enum 0: Primary - 0
qt.qpa.eglfs.kms:     enum 1: Overlay - 1
qt.qpa.eglfs.kms:     enum 2: Cursor - 2
qt.qpa.eglfs.kms: plane 1: id = 4001 countFormats = 34 possibleCrtcs = 0x1 supported formats = RA12 AR15 RA15 RG16 XR24 XB24 AR24 AB24 AR30 AB30 AB4H R101 R100 B101 B100 AS24 XS24 YUYV UYVY NV12 NV21 NV16 NV61 NV24 NV42 YU12 YV12 YU24 YV24 P210 P010 P012 HD01 UHD0 
qt.qpa.eglfs.kms:   property 0: id = 40017 name = 'SRC_X'
qt.qpa.eglfs.kms:   type is RANGE, value is 0, possible values are:
qt.qpa.eglfs.kms:     0
qt.qpa.eglfs.kms:   property 1: id = 40018 name = 'SRC_Y'
qt.qpa.eglfs.kms:   type is RANGE, value is 0, possible values are:
qt.qpa.eglfs.kms:     0
qt.qpa.eglfs.kms:   property 2: id = 40019 name = 'SRC_W'
qt.qpa.eglfs.kms:   type is RANGE, value is 0, possible values are:
qt.qpa.eglfs.kms:     0
qt.qpa.eglfs.kms:   property 3: id = 40020 name = 'SRC_H'
qt.qpa.eglfs.kms:   type is RANGE, value is 0, possible values are:
qt.qpa.eglfs.kms:     0
qt.qpa.eglfs.kms:   property 4: id = 40021 name = 'zpos'
qt.qpa.eglfs.kms:   type is RANGE, value is 20, possible values are:
qt.qpa.eglfs.kms:     20
qt.qpa.eglfs.kms:   property 5: id = 40022 name = 'alpha'
qt.qpa.eglfs.kms:   type is RANGE, value is 255, possible values are:
qt.qpa.eglfs.kms:     255
qt.qpa.eglfs.kms:   property 6: id = 40023 name = 'CRTC_X'
qt.qpa.eglfs.kms:   type is RANGE, value is 0, possible values are:
qt.qpa.eglfs.kms:     0
qt.qpa.eglfs.kms:   property 7: id = 40024 name = 'CRTC_Y'
qt.qpa.eglfs.kms:   type is RANGE, value is 0, possible values are:
qt.qpa.eglfs.kms:     0
qt.qpa.eglfs.kms:   property 8: id = 40025 name = 'CRTC_W'
qt.qpa.eglfs.kms:   type is RANGE, value is 0, possible values are:
qt.qpa.eglfs.kms:     0
qt.qpa.eglfs.kms:   property 9: id = 40026 name = 'CRTC_H'
qt.qpa.eglfs.kms:   type is RANGE, value is 0, possible values are:
qt.qpa.eglfs.kms:     0
qt.qpa.eglfs.kms:   property 10: id = 40027 name = 'CRTC_ID'
qt.qpa.eglfs.kms:   type is OBJECT
qt.qpa.eglfs.kms:   property 11: id = 40028 name = 'FB_ID'
qt.qpa.eglfs.kms:   type is OBJECT
qt.qpa.eglfs.kms:   property 12: id = 40029 name = 'IN_FENCE_FD'
qt.qpa.eglfs.kms:   type is OBJECT
qt.qpa.eglfs.kms:   property 13: id = 40030 name = 'IN_FORMATS'
qt.qpa.eglfs.kms:   type is BLOB
qt.qpa.eglfs.kms:   property 14: id = 40031 name = 'pixel blend mode'
qt.qpa.eglfs.kms:   type is ENUM, value is 1, possible values are:
qt.qpa.eglfs.kms:     enum 0: None - 0
qt.qpa.eglfs.kms:     enum 1: Pre-multiplied - 1
qt.qpa.eglfs.kms:     enum 2: Coverage - 2
qt.qpa.eglfs.kms:   property 15: id = 40032 name = 'color range'
qt.qpa.eglfs.kms:   type is ENUM, value is 0, possible values are:
qt.qpa.eglfs.kms:     enum 0: Full - 0
qt.qpa.eglfs.kms:     enum 1: Limited - 1
qt.qpa.eglfs.kms:   property 16: id = 40033 name = 'type'
qt.qpa.eglfs.kms:   type is ENUM, value is 1, possible values are:
qt.qpa.eglfs.kms:     enum 0: Primary - 0
qt.qpa.eglfs.kms:     enum 1: Overlay - 1
qt.qpa.eglfs.kms:     enum 2: Cursor - 2
qt.qpa.eglfs.kms: plane 2: id = 4002 countFormats = 34 possibleCrtcs = 0x1 supported formats = RA12 AR15 RA15 RG16 XR24 XB24 AR24 AB24 AR30 AB30 AB4H R101 R100 B101 B100 AS24 XS24 YUYV UYVY NV12 NV21 NV16 NV61 NV24 NV42 YU12 YV12 YU24 YV24 P210 P010 P012 HD01 UHD0 
qt.qpa.eglfs.kms:   property 0: id = 40034 name = 'SRC_X'
qt.qpa.eglfs.kms:   type is RANGE, value is 0, possible values are:
qt.qpa.eglfs.kms:     0
qt.qpa.eglfs.kms:   property 1: id = 40035 name = 'SRC_Y'
qt.qpa.eglfs.kms:   type is RANGE, value is 0, possible values are:
qt.qpa.eglfs.kms:     0
qt.qpa.eglfs.kms:   property 2: id = 40036 name = 'SRC_W'
qt.qpa.eglfs.kms:   type is RANGE, value is 0, possible values are:
qt.qpa.eglfs.kms:     0
qt.qpa.eglfs.kms:   property 3: id = 40037 name = 'SRC_H'
qt.qpa.eglfs.kms:   type is RANGE, value is 0, possible values are:
qt.qpa.eglfs.kms:     0
qt.qpa.eglfs.kms:   property 4: id = 40038 name = 'zpos'
qt.qpa.eglfs.kms:   type is RANGE, value is 30, possible values are:
qt.qpa.eglfs.kms:     30
qt.qpa.eglfs.kms:   property 5: id = 40039 name = 'alpha'
qt.qpa.e [...]

2022-04-29 13:07 UTC, benediktley commented
I did some experiments switching HDMI screens and ran into some strange behavior. When I start the app having a screen connected I get the output `qt.qpa.eglfs.kms: Mode already set` (second last line in the log from my previous post). When I disconnect the screen while the app is running and connect another screen to the same HDMI port and then stop and restart the application I get the app rendered on screen and the log entry changes to `qt.qpa.eglfs.kms: Setting mode`

2022-04-29 16:12 UTC, kekiefer commented
What happens if you set `QT_QPA_EGLFS_ALWAYS_SET_MODE=1` in your environment?

2022-04-29 16:53 UTC, benediktley commented
Cool. That did the trick. Thanks!

2022-04-29 16:54 UTC, kekiefer commented
Do you have a minute to check out the same patches we have on master and let me know if that workaround is still required for you? I didn't need it with my setup, and it doesn't look like a Qt difference (at least not that is immediately obvious), so I'd like to understand this a bit better.

2022-04-29 17:37 UTC, benediktley commented
Sure. I will built can image from master overnight and test it tomorrow.

2022-04-30 10:08 UTC, benediktley commented
I built an image based on tegra-demo from master branch and experience the same behavior as with dunfell. `QT_QPA_EGLFS_ALWAYS_SET_MODE=1` is still necessary. Some additional information about my setup: 
I have an [AAEON BOXER-8253AI](https://www.aaeon.com/en/p/nvidia-jetson-xavier-nx-ai-edge-poe-boxer-8253ai) with Xavier NX module. Not sure if the HDMI port from the AAEON carrier board is connected to the SoC in the same way as the NVIDIA dev board.

2022-05-02 23:23 UTC, kekiefer commented
I've updated this PR to include setting the mode by default, so you shouldn't need that environment variable. Give it a try and let me know.

2022-05-06 16:30 UTC, benediktley commented
Works for me now. Mode is set properly without environment variable. Thanks!

2022-05-06 16:37 UTC, merged